### PR TITLE
Add file with information to create boot files to build Chez

### PR DESCRIPTION
**Pull request by pmatos**

### CODE REVIEW

**Review by jessealama — CHANGES_REQUESTED** [review]
Can we add ARM 32 to the list (in "Setup the boot files...")?

**Comment by pmatos** [comment]
> Can we add ARM 32 to the list (in "Setup the boot files...")?

I don't think this works on ARM 32... at least it's completely untested. I can give it a go tomorrow and see...

**Comment by pmatos** [comment]
Once the Actions PR https://github.com/racket/ChezScheme/pull/22 gets merged upstream, we can then add our own jobs to it and self-hosted GitHub runners on rpi3, rpi4 and unleashed to test arm32, arm64 and rv64.

**Comment by pmatos** [comment]
> Can we add ARM 32 to the list (in "Setup the boot files...")?

On an ARM32, the bootstrap process does this:
```
$ MACH=arm32le racket -l cs-bootstrap
Assuming current directory has Chez Scheme sources
Use /home/pi/.racket/7.2/pkgs/cs-bootstrap/.
Use /home/pi/dev/ChezScheme/nanopass
Use /home/pi/dev/ChezScheme/s
Check /home/pi/dev/ChezScheme/boot/arm32le
Load nanopass
Apply nanopass patch
Load cmacro parts
Load enum
Load cprep
Load expander
Install evaluator
Load cmacros using expander
Continue loading expander
Initialize system libraries
Load nanopass using expander
Load priminfo and primvars
Load expander using expander
Initialize system libraries in bootstrapped expander
Declare nanopass in bootstrapped expander
Load some io.ss declarations
Load some strip.ss declarations
Load some 7.ss declarations
Load most front.ss declarations
Define $filter-foreign-type
Load mkheader
Generate headers
Load mkgc
Generate GC
Load ftype.ss
Load fasl.ss
Load reloc.ss
Load format.ss
Load cp0.ss
Load cpvalid.ss
Load cpcheck.ss
Load cpletrec.ss
Load cpcommonize.ss
Load cpnanopass.ss
Load compile.ss
Load back.ss
compiling library.ss with output to /home/pi/dev/ChezScheme/boot/arm32le/library.so
compiler-internal: find-home!: spilled unspillable #s((|{uvar unique80930}| #(0 1 2 3 4 5 6 7 8 9 10 11 12) |{var unique80904}| 3 #(0 1 2)) 8 #s((|{cset unique126435}| #(0 1)) 0 0) #s((|{cset unique126435}| #(0 1)) 12 512) ulr #f uptr (#s((|{reg unique80906}| #(0 1 2 3 4) |{var unique80904}| 3 #(0 1 2)) 1 #s((|{cset unique126435}| #(0 1)) 0 0) #s((|{cset unique126435}| #(0 1)) 12 2031) %ac0 4 20 #t #f) #s((|{reg unique80906}| #(0 1 2 3 4) |{var unique80904}| 3 #(0 1 2)) 2 #s((|{cset unique126435}| #(0 1)) 0 0) #s((|{cset unique126435}| #(0 1)) 12 2047) %xp 6 56 #t #f) #s((|{reg unique80906}| #(0 1 2 3 4) |{var unique80904}| 3 #(0 1 2)) 3 #s((|{cset unique126435}| #(0 1)) 0 0) #s((|{cset unique126435}| #(0 1)) 12 256) %ts 12 64 #f #f) #s((|{reg unique80906}| #(0 1 2 3 4) |{var unique80904}| 3 #(0 1 2)) 4 #s((|{cset unique126435}| #(0 1)) 0 0) #s((|{cset unique126435}| #(0 1)) 12 4039) %td 11 68 #t #f) #s((|{reg unique80906}| #(0 1 2 3 4) |{var unique80904}| 3 #(0 1 2)) 5 #s((|{cset unique126435}| #(0 1)) 0 0) #s((|{cset unique126435}| #(0 1)) 12 #t) %cp 7 32 #t #f) #s((|{reg unique80906}| #(0 1 2 3 4) |{var unique80904}| 3 #(0 1 2)) 6 #s((|{cset unique126435}| #(0 1)) 0 0) #s((|{cset unique126435}| #(0 1)) 12 #t) %r0 0 0 #f #f) #s((|{reg unique80906}| #(0 1 2 3 4) |{var unique80904}| 3 #(0 1 2)) 7 #s((|{cset unique126435}| #(0 1)) 0 0) #s((|{cset unique126435}| #(0 1)) 12 #t) %r1 1 4 #f #f) #s((|{reg unique80906}| #(0 1 2 3 4) |{var unique80904}| 3 #(0 1 2)) 8 #s((|{cset unique126435}| #(0 1)) 0 0) #s((|{cset unique126435}| #(0 1)) 12 #t) %r2 2 8 #f #f) #s((|{reg unique80906}| #(0 1 2 3 4) |{var unique80904}| 3 #(0 1 2)) 9 #s((|{cset unique126435}| #(0 1)) 0 0) #s((|{cset unique126435}| #(0 1)) 12 #t) %r3 3 12 #f #f)) 15 #f #f () 11 #f 0 0 0)
```

I think we shouldn't mention arm32 in the docs yet until we (or someone) fixes this. OK to merge?

**Comment by jessealama** [comment]
I agree -- this looks pretty bad. Let's drop aarch32 from the list for now.

**Comment by pmatos** [comment]
@jessealama can you pls mark the PR as approved so I can merge pls?

**Review by jessealama — APPROVED** [review]

**Comment by jessealama** [comment]
done

**Pull request merged**
